#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    FordTrucksBelux-backend-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^fordtrucksbelux-backend\.ddev\.site$`)
      
      service: "FordTrucksBelux-backend-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "FordTrucksBelux-backend-redirectHttps"
    FordTrucksBelux-backend-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^fordtrucksbelux-backend\.ddev\.site$`)
      
      service: "FordTrucksBelux-backend-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "FordTrucksBelux-backend-redirectHttps"
    
    
    
    FordTrucksBelux-backend-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^fordtrucksbelux-backend\.ddev\.site$`)
      
      service: "FordTrucksBelux-backend-web-80"
      ruleSyntax: v3
      
      tls: true
      
    FordTrucksBelux-backend-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^fordtrucksbelux-backend\.ddev\.site$`)
      
      service: "FordTrucksBelux-backend-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    FordTrucksBelux-backend-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    FordTrucksBelux-backend-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-FordTrucksBelux-backend-web:80
        
    FordTrucksBelux-backend-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-FordTrucksBelux-backend-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/FordTrucksBelux-backend.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/FordTrucksBelux-backend.key