#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    Ford-CMS-Backend-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^ford-cms-backend\.ddev\.site$`)
      
      service: "Ford-CMS-Backend-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "Ford-CMS-Backend-redirectHttps"
    Ford-CMS-Backend-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^ford-cms-backend\.ddev\.site$`)
      
      service: "Ford-CMS-Backend-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "Ford-CMS-Backend-redirectHttps"
    
    
    
    Ford-CMS-Backend-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^ford-cms-backend\.ddev\.site$`)
      
      service: "Ford-CMS-Backend-web-80"
      ruleSyntax: v3
      
      tls: true
      
    Ford-CMS-Backend-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^ford-cms-backend\.ddev\.site$`)
      
      service: "Ford-CMS-Backend-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    Ford-CMS-Backend-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    Ford-CMS-Backend-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-Ford-CMS-Backend-web:80
        
    Ford-CMS-Backend-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-Ford-CMS-Backend-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/Ford-CMS-Backend.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/Ford-CMS-Backend.key