name: SevenArts
type: php
docroot: htdocs/public
php_version: "8.4"
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mysql
    version: "8.0"
host_db_port: "59064"
use_dns_when_possible: true
composer_version: "2"
composer_root: htdocs/
web_environment: []
corepack_enable: false
disable_settings_management: true
